IF NOT EXISTS (
	SELECT 1
	FROM sys.tables
	WHERE name = 'Users'
		AND schema_id = SCHEMA_ID('dbo')
) BEGIN CREATE TABLE dbo.Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	Username NVARCHAR(150) NOT NULL UNIQUE,
	Password NVARCHAR(MAX) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
END;
GO IF NOT EXISTS (
		SELECT 1
		FROM sys.tables
		WHERE name = 'Articles'
			AND schema_id = SCHEMA_ID('dbo')
	) BEGIN CREATE TABLE dbo.Articles (
		Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
		Title NVARCHAR(255) NOT NULL,
		Content NVARCHAR(MAX) NOT NULL,
		AuthorId UNIQUEIDENTIFIER NOT NULL,
		CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
		CONSTRAINT FK_Articles_Users FOREIGN KEY (AuthorId) REFERENCES dbo.Users(Id)
	);
END;
GO