CREATE TABLE IF NOT EXISTS Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	Username NVARCHAR(150) NOT NULL UNIQUE,
	Password NVARCHAR(MAX) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO CREATE TABLE IF NOT EXISTS Articles (
		Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
		Title NVARCHAR(255) NOT NULL,
		Content NVARCHAR(MAX) NOT NULL,
		AuthorId UNIQUEIDENTIFIER NOT NULL,
		CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
		CONSTRAINT FK_Articles_Users FOREIGN KEY (AuthorId) REFERENCES Users(Id)
	);
GO